VERSION="1.6.5"

FROM("docker://docker.io/library/debian:buster-slim", "zerotier", "zerotier")
SCRIPT("rmusers")
SCRIPT("rmsuid")
COPY("01_nodoc", "/etc/dpkg/dpkg.cfg.d/01_nodoc")
RUN("cp --remove-destination /usr/share/zoneinfo/UTC /etc/localtime")
APT_GET("update")
APT_GET("full-upgrade")
APT_GET("install curl gnupg dirmngr ca-certificates")
COPY("zerotier.gpg")
RUN("apt-key add /zerotier.gpg")
RM("/zerotier.gpg")
COPY("zerotier.list", "/etc/apt/sources.list.d/zerotier.list")
APT_GET("update")
APT_GET("install zerotier-one=%s" % VERSION)
APT_GET("purge curl gnupg dirmngr ca-certificates")
APT_PURGE("sysvinit-utils bash tzdata e2fsprogs e2fslibs util-linux mount login hostname fdisk bsdutils findutils")
APT_GET("--purge autoremove")
APT_GET("autoclean")
PURGE("docs")
PURGE("perl")
PURGE("dpkg")
PURGE("userland")
ENTRYPOINT("/usr/sbin/zerotier-one")
COMMIT("zerotier-one:%s" % VERSION)
